FROM mysql:5.7.26

ENV MYSQL_ALLOW_EMPTY_PASSWORD yes

# Add the content of the sql-scripts/ directory to your image
# All scripts in docker-entrypoint-initdb.d/ are automatically
# executed during container startup
COPY ./sql-scripts/ /docker-entrypoint-initdb.d/